extend type Document {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Document", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Document`.`generator`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  generatorId: UUID! @fdc_generated(from: "Document.generator", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Document`.`template`. It must match the value of `Template`.`id`. See `@ref` for how to customize it.
  """
  templateId: UUID! @fdc_generated(from: "Document.template", purpose: IMPLICIT_REF_FIELD)
}
extend type DocumentData {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "DocumentData", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `DocumentData`.`document`. It must match the value of `Document`.`id`. See `@ref` for how to customize it.
  """
  documentId: UUID! @fdc_generated(from: "DocumentData.document", purpose: IMPLICIT_REF_FIELD)
}
extend type Placeholder {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Placeholder", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Placeholder`.`template`. It must match the value of `Template`.`id`. See `@ref` for how to customize it.
  """
  templateId: UUID! @fdc_generated(from: "Placeholder.template", purpose: IMPLICIT_REF_FIELD)
}
extend type Template {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Template", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Template`.`owner`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  ownerId: UUID! @fdc_generated(from: "Template.owner", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
