extend type Query {
  """
  ✨ Look up a single `Document` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  document(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Document_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Document_FirstRow
  ): Document @fdc_generated(from: "Document", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DocumentData` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  documentData(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DocumentData_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DocumentData_FirstRow
  ): DocumentData @fdc_generated(from: "DocumentData", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Placeholder` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  placeholder(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Placeholder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Placeholder_FirstRow
  ): Placeholder @fdc_generated(from: "Placeholder", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Template` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  template(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Template_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Template_FirstRow
  ): Template @fdc_generated(from: "Template", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Document` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  documents(
    """
    Filter condition to narrow down the query results.
    """
    where: Document_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Document_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Document_Having
  ): [Document!]! @fdc_generated(from: "Document", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DocumentData` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  documentDatas(
    """
    Filter condition to narrow down the query results.
    """
    where: DocumentData_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DocumentData_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DocumentData_Having
  ): [DocumentData!]! @fdc_generated(from: "DocumentData", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Placeholder` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  placeholders(
    """
    Filter condition to narrow down the query results.
    """
    where: Placeholder_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Placeholder_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Placeholder_Having
  ): [Placeholder!]! @fdc_generated(from: "Placeholder", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Template` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  templates(
    """
    Filter condition to narrow down the query results.
    """
    where: Template_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Template_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Template_Having
  ): [Template!]! @fdc_generated(from: "Template", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
